tittle: Sumanth Chilupuri
logo: ![Headshot](https://github.com/SumanthChilupuri/sumanthchilupuri.github.io/assets/68773046/820e2d62-4f2a-46a5-97f3-b20be8257b0e)
show_downloads: false
theme: jekyll-theme-minimal
